#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* 

The skeleton of this file has been generated by the following call, within an R
session open in the main LiblineaR package directory:

tools::package_native_routine_registration_skeleton(".","./src/init.c")

It has been further edited so that the types of arguments of predictLinear and
trainLinear match the actual argument types, as specified by the .C call in the
LiblineaR.R and predict.R files. 

*/ 


/* .C calls */
extern void predictLinear(double *Y, double *X, double *W, int *decisionValues, double *DecisionValues, int *proba, double *Probabilities, 
        int *nbClass, int *nbDim, int *nbSamples, int *sparse, int *rowindex, int *colindex, double *bias, int *labels, int *type);

extern void trainLinear(double *W_ret, int* labels_ret, double *X, double *Y, int *nbSamples, int *nbDim, int *sparse, int *rowindex, int *colindex, 
                 double *bi, int *type, double *cost, double *epsilon, double* svr_eps, int *nrWi, double *Wi, int *WiLabels, int *cross, int *verbose, int *findC, int *useInitC);


        
static const R_CMethodDef CEntries[] = {
    {"predictLinear", (DL_FUNC) &predictLinear, 16},
    {"trainLinear",   (DL_FUNC) &trainLinear,   21},
    {NULL, NULL, 0}
};

void R_init_LiblineaR(DllInfo *dll)
{
    R_registerRoutines(dll, CEntries, NULL, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
